name: Linux build

on:
  - push
  - workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup
      run: |
        printf "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-12 main" |sudo tee /etc/apt/sources.list.d/llvm-toolchain-xenial-12.list
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key |sudo apt-key add -
        sudo apt update
        sudo apt install libffi-dev
        sudo apt install llvm-12-dev
        sudo apt install libwxgtk3.0-gtk3-dev
        sudo apt install libwxgtk-media3.0-gtk3-dev
    - name: Build
      run: |
        cd fractalstream-ui-wx
        cp stack.yaml.ubuntu stack.yaml
        stack build
