name: macOS build

on:
  - workflow_dispatch

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup
      run: |
        brew install haskell-stack
        brew install libffi
        brew install llvm-hs/llvm/llvm-12
        echo WX `which wx-config`
        brew install wxwidgets@3.2
        ln -s `which wx-config-3.2` $(dirname `which wx-config-3.2`)/wx-config
        ln -s `which wxrc-3.2` $(dirname `which wxrc-3.2`)/wxrc
        echo `which wx-config`
        wx-config --list
        wx-config --version
        wx-config --version-full
        wx-config --libs
    - name: Build
      run: |
        cd fractalstream-ui-wx
        cp stack.yaml.macos stack.yaml
        stack build
